version: "3.9"
services:
  chinook-restapi:
    build: .
    image: aspnetapp:latest
    container_name: chinook-restapi
    restart: always
    ports:
      - "8090:80"
    networks:
      - chinook-network

networks:
  chinook-network:
    name: chinook-network
