version: "3.9"

# >>> SERVICES >>>
services:
  # >>> REACT WEB >>>
  react-web:
    image: react/react-web:1.0.0
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: react-web
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "3000:80"
    networks:
      - react-network
  # <<< REACT WEB <<<

# >>> NETWORKS >>>
networks:
  react-network:
    driver: bridge
